basePath: /
host: localhost:8080
info:
  contact:
    email: gkabitakis@gmail.com
    name: gkampitakis
  description: Template for spinning up a gofiber server
  license:
    name: https://opensource.org/licenses/MIT
  title: Gofiber Template Server
  version: 1.0.0
paths:
  /:
    get:
      consumes:
      - text/plain
      description: Default func prints hello world
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Prints Hello World
      tags:
      - template
  /health:
    get:
      consumes:
      - text/plain
      description: Route reporting health of service
      responses:
        "200":
          description: This can be dynamic and add more fields in checks
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: The route can return 500 in case of failed check,timeouts or
            panic
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Healthcheck route
      tags:
      - health
  /hello/:name:
    get:
      consumes:
      - text/plain
      description: Hello func just Greets with the name provided in params
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Greets user
      tags:
      - template
swagger: "2.0"
